package com.codeagent.rag.model;

public enum EvidenceType {
    GITLAB_MERGE_REQUEST,
    GITLAB_COMMITS,
    GITLAB_DIFF,
    GITLAB_REVIEW_COMMENTS,
    JENKINS_BUILD_STATUS,
    JENKINS_TEST_REPORT,
    JENKINS_CONSOLE_LOG,
    JENKINS_ARTIFACTS,
    SONAR_QUALITY_GATE,
    SONAR_ISSUES,
    SONAR_MEASURES,
    JAVA_CODE,
    MARKDOWN,
    DOCUMENT
}
