package com.codeagent.common.enums;

public enum ModelTaskType {
    QUERY_UNDERSTANDING,
    INTENT_CLASSIFICATION,
    PLANNING,
    TOOL_SELECTION,
    REACT_TOOL_PLANNING,
    OBSERVATION_REFLECTION,
    EVIDENCE_SUMMARY,
    CRITIQUE,
    REPLAN,
    FINAL_REPORT,
    CODE_ANALYSIS,
    EPISODE_CONSOLIDATION
}
