package com.codeagent.common.enums;

public enum TaskStatus {
    CREATED,
    QUERY_UNDERSTANDING,
    INTENT_CLASSIFYING,
    AMBIGUITY_CHECKING,
    NEEDS_CLARIFICATION,
    CONTEXT_RESOLVING,
    PLANNING,
    MCP_REACT_EXECUTING,
    EXECUTING,
    EVIDENCE_BUILDING,
    CRITIQUING,
    REPLANNING,
    FINALIZING,
    COMPLETED,
    FAILED
}
